name: Destroy Infrastructure

on:
  workflow_dispatch:  # Allows manual trigger from GitHub Actions

env:
  AWS_REGION: ap-south-1
  ECR_REPO: glps-demo-ecr
  CLUSTER_NAME: glps-demo-eks-cluster

jobs:
  destroy:
    runs-on: ubuntu-latest
    

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.0

      - name: Terraform Init
        run: | 
          terraform init \
            -backend-config="bucket=glps-dev-backend-bucket" \
            -backend-config="region=ap-south-1" \
            -backend-config="key=eks/terraform.tfstate"
          env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_DEFAULT_REGION: ap-south-1

      - name: Terraform Destroy
        working-directory: ./terraform
        run: |
          terraform destroy -auto-approve
