name: Terraform Destroy

on:
  workflow_dispatch:  # Allows manual trigger from GitHub UI

env:
  AWS_REGION: ap-south-1
  ECR_REPO: glps-demo-ecr
  CLUSTER_NAME: glps-demo-eks-cluster
  AWS_ACCOUNT_ID: $(aws sts get-caller-identity --query Account --output text)

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6  # Use your preferred version

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init
      - name: Set image URL for Terraform
        run: echo "WEB_IMAGE=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO}:latest" >> $GITHUB_ENV

      - name: Terraform Destroy
        working-directory: ./terraform
        run: terraform destroy -auto-approve -var="web_image=${WEB_IMAGE}"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "ap-south-1"  # Change to your region
